services:
  singlestore:
    image: ghcr.io/singlestore-labs/singlestoredb-dev:latest
    platform: linux/amd64
    restart: unless-stopped
    ports:
      - "3307:3306"
    environment:
      ROOT_PASSWORD: ${SINGLESTORE_PASSWORD}
    volumes:
      - /mnt/singlestore:/data
