services:
  singlestore:
    image: ghcr.io/singlestore-labs/singlestoredb-dev:latest
    platform: linux/amd64
    restart: unless-stopped
    ports:
      - "3307:3306"
    environment:
      ROOT_PASSWORD: ${SINGLESTORE_PASSWORD}
    volumes:
      - singlestore_data:/var/lib/memsql

  postgres:
    image: postgres:latest
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mysql:
    image: mysql:latest
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB}
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  singlestore_data:
  postgres_data:
  mysql_data:
